
#NCU
SET(NCU_BASE_PATH  ${NCU_PATH}/mcs)
SET(NCU_DOMAIN_PATH   ${NCU_BASE_PATH}/domain)

SET(DOMAIN_COMMON_PATH   ${NCU_DOMAIN_PATH}/common)
SET(DOMAIN_CFG_PATH   ${DOMAIN_COMMON_PATH}/dbcfg)
SET(DOMAIN_MEMCFG_PATH ${DOMAIN_COMMON_PATH}/memcfg)
SET(DOMAIN_DBAPP_PATH ${DOMAIN_COMMON_PATH}/dbapp)
SET(DOMAIN_PMREPORT_PATH ${DOMAIN_COMMON_PATH}/pmReport)

SET(DOMAIN_MODEL_PATH   ${NCU_DOMAIN_PATH}/model)
SET(DOMAIN_GDMM_PATH ${DOMAIN_MODEL_PATH}/gdmm)
SET(DOMAIN_JOB_PATH ${DOMAIN_MODEL_PATH}/job)
SET(DOMAIN_ENCODE_PATH ${DOMAIN_MODEL_PATH}/encode)
SET(DOMAIN_REASM_PATH ${DOMAIN_MODEL_PATH}/reasm)


SET(DOMAIN_UTILS_PATH   ${NCU_DOMAIN_PATH}/utils)
SET(DOMAIN_UTILS_ROUTE_PATH  ${DOMAIN_UTILS_PATH}/route)


SET(NCU_UI_PATH   ${NCU_BASE_PATH}/ui)
SET(NCU_INSFRA_PATH ${NCU_BASE_PATH}/infrastructure)

SET(NCU_APP_PATH ${NCU_BASE_PATH}/application)
SET(APP_PKT_SOLVE_PATH  ${NCU_APP_PATH}/pktsolve)
SET(APP_HTTPLINK_PATH  ${NCU_APP_PATH}/httplink)
SET(APP_SUBSCRIBE_PATH  ${NCU_APP_PATH}/subscribe)
SET(APP_REPORT_PATH  ${NCU_APP_PATH}/report)
SET(APP_TRACE_PATH  ${NCU_APP_PATH}/trace)
SET(APP_HEART_PATH  ${NCU_APP_PATH}/heart)
SET(APP_UCOMMSG_PATH  ${NCU_APP_PATH}/UcomMsg)

INCLUDE_DIRECTORIES(${NCU_DOMAIN_PATH}/common)
INCLUDE_DIRECTORIES(${NCU_DOMAIN_PATH}/common/pub)
INCLUDE_DIRECTORIES(${NCU_DOMAIN_PATH}/common/sccuclient/include)
INCLUDE_DIRECTORIES(${DOMAIN_CFG_PATH}/include) 
INCLUDE_DIRECTORIES(${DOMAIN_MEMCFG_PATH}/include)
INCLUDE_DIRECTORIES(${DOMAIN_DBAPP_PATH}/entryFunc/include)
INCLUDE_DIRECTORIES(${DOMAIN_DBAPP_PATH}/commTable/include)
INCLUDE_DIRECTORIES(${DOMAIN_DBAPP_PATH}/mcsTable/include)
INCLUDE_DIRECTORIES(${DOMAIN_DBAPP_PATH}/dbaccess/include)
INCLUDE_DIRECTORIES(${DOMAIN_PMREPORT_PATH}/include)

INCLUDE_DIRECTORIES(${NCU_DOMAIN_PATH}/model)
INCLUDE_DIRECTORIES(${DOMAIN_GDMM_PATH}/include)
INCLUDE_DIRECTORIES(${DOMAIN_JOB_PATH}/include)
INCLUDE_DIRECTORIES(${DOMAIN_ENCODE_PATH}/include)
INCLUDE_DIRECTORIES(${DOMAIN_REASM_PATH}/include)

INCLUDE_DIRECTORIES(${NCU_DOMAIN_PATH}/utils)
INCLUDE_DIRECTORIES(${DOMAIN_UTILS_ROUTE_PATH}/include)


INCLUDE_DIRECTORIES(${NCU_DOMAIN_PATH}/infrastructure)
INCLUDE_DIRECTORIES(${NCU_INSFRA_PATH}/log/include)

INCLUDE_DIRECTORIES(${APP_PKT_SOLVE_PATH}/include)
INCLUDE_DIRECTORIES(${APP_HTTPLINK_PATH}/include)
INCLUDE_DIRECTORIES(${APP_SUBSCRIBE_PATH}/include)
INCLUDE_DIRECTORIES(${APP_REPORT_PATH}/include)
INCLUDE_DIRECTORIES(${APP_TRACE_PATH}/include)
INCLUDE_DIRECTORIES(${APP_HEART_PATH}/include)
INCLUDE_DIRECTORIES(${NCU_UI_PATH}/include)
INCLUDE_DIRECTORIES(${APP_UCOMMSG_PATH}/include)

INCLUDE_DIRECTORIES(${NCU_PATH}/entry)
