SET(ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/..")
FILE(STRINGS ${ROOT_PATH}/build/VERSION.txt CURRENT_VERSION)
SET(CMAKE_INSTALL_PREFIX "${ROOT_PATH}/output/ncu_sc/${CURRENT_VERSION}")
INSTALL(TARGETS ${TARGET_NAME}
    RUNTIME DESTINATION bin
    LIBRARY DESTINATION lib
    ARCHIVE DESTINATION lib
)
